### ISSUE TITLE
rebuild_index rake task fails

### ISSUE THREAD

**Issue by mnewt** [jkraemer/redmine_postgresql_search#3]
On a new redmine 3.2.1 installation, indexing doesn't appear to work. Is this a configuration issue?

Thanks for your help

``` shell
>  uname -a
Linux redmine 4.4.0-17-generic #33-Ubuntu SMP Tue Mar 29 17:17:28 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> RAILS_ENV=production bundle exec rake redmine_postgresql_search:rebuild_index
rake aborted!
NameError: uninitialized constant RedminePostgresqlSearch::Patches::Searchable::ClassMethods::FulltextIndex
/opt/redmine-3.2.1/plugins/redmine_postgresql_search-master/lib/redmine_postgresql_search/patches/searchable.rb:9:in `block in rebuild_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.5.2/lib/active_record/transactions.rb:220:in `transaction'
/opt/redmine-3.2.1/plugins/redmine_postgresql_search-master/lib/redmine_postgresql_search/patches/searchable.rb:8:in `rebuild_index'
/opt/redmine-3.2.1/plugins/redmine_postgresql_search-master/lib/redmine_postgresql_search.rb:53:in `block in rebuild_indices'
/opt/redmine-3.2.1/plugins/redmine_postgresql_search-master/lib/redmine_postgresql_search.rb:52:in `each'
/opt/redmine-3.2.1/plugins/redmine_postgresql_search-master/lib/redmine_postgresql_search.rb:52:in `rebuild_indices'
/opt/redmine-3.2.1/plugins/redmine_postgresql_search-master/lib/tasks/redmine_postgresql_search.rake:5:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine_postgresql_search:rebuild_index
(See full trace by running task with --trace)
```

**Comment by jkraemer** [comment]
I just tried and could not reproduce this. It might be that your directory naming is the problem  - Redmine plugin directories should always be named exactly like the plugin unless explicitly stated otherwise. So instead of `redmine_postgresql_search-master` try `redmine_postgresql_search` .

**Comment by mnewt** [comment]
Awesome, thanks for checking on this. I renamed the directory and it worked. Cheers!
